spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  graphql:
    schema:
      # This tells Spring GraphQL to look for .graphqls schema files inside src/main/resources/graphql/
      locations: classpath:graphql/
    graphiql:
      enabled: true # Enable the GraphiQL Playground

